#!/bin/bash

START_PATH=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts
COMMAND=$START_PATH/TF_run_euclidlike.py

TRAINING_MOM=/vol/euclid5/euclid5_raid3/aanavarroa/trainings_eu
WORK_PATH=$TRAINING_MOM/wm_varpsf_vardensity-w_s_f_r_psf-m_g12_frac
POINT_MODEL_CONFIG=$TRAINING_MOM/tp-varpsf-grid-trucat-nw-adamompsf-net10/training/members/_bestmember/bestmember.cfg
POINT_MODEL_WEIGHTS=$TRAINING_MOM/tp-varpsf-grid-trucat-nw-adamompsf-net10/training/members/_bestmember/bestmember_weights.ckpt
G_NORMER=$TRAINING_MOM/tp-varpsf-grid-trucat-nw-adamompsf-net10/training/normers/tp_input_adamom_g1adamom_g2adamom_sigmaadamom_fluxadamom_rho4psf_adamom_g1psf_adamom_g2psf_adamom_sigmapsf_adamom_rho4_normer.pkl
G_CONFIG=$START_PATH/g_net2.cfg
G_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "adamom_flux" "adamom_rho4" "psf_adamom_g1" "psf_adamom_g2" "psf_adamom_sigma" "psf_adamom_rho4")


WM_CONFIG=$START_PATH/wm_10x3.cfg
CATS_MOM=/vol/euclid5/euclid5_raid3/aanavarroa/catalogs/MomentsML/fullimages_constimg_euclid
CATS_MOM2=/vol/euclidraid4/data/aanavarroa/catalogs/MomentsML/fullimages_constimg_euclid
WM_CAT=$CATS_MOM/tw-varpsf-blended-vardensity-big/adamom_sexcat_w/groupcat.pkl
WM_VCAT=$CATS_MOM2/vo-varpsf-blended-vardensity-big/adamom_sexcat_w/groupcat.pkl
W_FEATURES=("adamom_sigma" "adamom_flux" "adamom_rho4" "psf_adamom_g1" "psf_adamom_g2" "psf_adamom_sigma" "psf_adamom_rho4")
M_FEATURES=("adamom_g1" "adamom_g2" "fracpix_md")
EPOCHS=2000
FINE_EPOCHS=5000
LEARNING_RATE=0.01

python $COMMAND  --workdir=$WORK_PATH --g_config=$G_CONFIG --wm_config=$WM_CONFIG --g_features ${G_FEATURES[@]} --w_features ${W_FEATURES[@]} --m_features ${M_FEATURES[@]} --wm_cat=$WM_CAT --wm_vcat=$WM_VCAT  --g_model_config=$POINT_MODEL_CONFIG --g_model_weights=$POINT_MODEL_WEIGHTS --epochs=$EPOCHS --fine_epochs=$FINE_EPOCHS --learning_rate=$LEARNING_RATE --g_normer=$G_NORMER --validate_wm  #--train_wm --finetune
 
