#!/bin/bash

START_PATH=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts_2comp
COMMAND=$START_PATH/TF_run_euclidlike_2comp.py

TRAINING_MOM=/vol/euclidraid4/data/aanavarroa/trainings_eu_2comp-flagship/
WORK_PATH=$TRAINING_MOM/w-grid-trucat-nw-ss_10nodes

GDIR=/g-grid-trucat-nw-ss_10nodes/training_back/
#GDIR=/g-grid-trucat-nw-ss_10nodes_varback/training_old/
POINT_MODEL_CONFIG=$TRAINING_MOM/$GDIR/members/_bestmember/bestmember.cfg
POINT_MODEL_WEIGHTS=$TRAINING_MOM/$GDIR/members/_bestmember/bestmember_weights.ckpt
G_NORMER=$TRAINING_MOM/$GDIR/normers/tp_input_adamom_g1adamom_g2adamom_sigmaadamom_fluxadamom_rho4_normer.pkl
G_CONFIG=$START_PATH/g.cfg
G_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "adamom_flux" "adamom_rho4")
TARGETS=("tru_s1" "tru_s2")

W_CONFIG=$START_PATH/w_10x10.cfg
CATS_MOM=/vol/euclidraid4/data/aanavarroa/catalogs/MomentsML/fullimages_constimg_euclid-flagship/
G_CAT=$CATS_MOM/tp-bulgedisk-constpsf-constback-grid/adamom_trucat_nw_ss/groupcat.fits
W_CAT=$CATS_MOM/tw-bulgedisk-constpsf-constback-grid-big/adamom_trucat_nw_ss/groupcat.fits
W_VCAT=$CATS_MOM/tw-bulgedisk-constpsf-constback-grid-big/adamom_trucat_nw_ss/groupcat.fits
W_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "adamom_flux" "adamom_rho4")
EPOCHS=5000
FINE_EPOCHS=100
LEARNING_RATE=0.1

cd $START_PATH

python $COMMAND  --workdir=$WORK_PATH --g_config=$G_CONFIG --w_config=$W_CONFIG --g_features ${G_FEATURES[@]} --w_features ${W_FEATURES[@]} --targets ${TARGETS[@]} --g_cat=$G_CAT --w_cat=$W_CAT --w_vcat=$W_VCAT  --g_model_config=$POINT_MODEL_CONFIG --g_model_weights=$POINT_MODEL_WEIGHTS --g_normer=$G_NORMER --epochs=$EPOCHS --fine_epochs=$FINE_EPOCHS --learning_rate=$LEARNING_RATE  --validate_w #--train_w --nbatch=10 --use_val #--finetune  #--use_val
 
