#!/bin/bash

START_PATH=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts
COMMAND=$START_PATH/TF_run_fiducial.py

WORK_PATH=/vol/euclid5/euclid5_raid3/aanavarroa/trainings/tp-vp

G_CONFIG=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts/g.cfg
CATS_MOM=/vol/euclid5/euclid5_raid3/aanavarroa/catalogs/MomentsML/fullimages_constimg_fiducial
G_CAT=$CATS_MOM/tp/meas_withsex2/groupcats_withsex.fits
G_VCAT=$CATS_MOM/vp/meas_withsex2/groupcats_withsex.fits
G_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "adamom_flux" "adamom_rho4")
EPOCHS=10000
FINE_EPOCHS=1000
LEARNING_RATE=0.01

python $COMMAND  --workdir=$WORK_PATH --g_config=$G_CONFIG --g_features ${G_FEATURES[@]} --g_cat=$G_CAT --g_vcat=$G_VCAT --epochs=$EPOCHS --fine_epochs=$FINE_EPOCHS --learning_rate=$LEARNING_RATE --train_g --validate_g
 
