#!/bin/bash

START_PATH=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts
COMMAND=$START_PATH/TF_run_euclidlike.py

WORK_PATH=/vol/euclid5/euclid5_raid3/aanavarroa/trainings_eu/tp-varpsf-grid-trucat-adamompsf-net10

G_CONFIG=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts/g_net2.cfg
CATS_MOM=/vol/euclid2/euclid2_raid2/aanavarroa/catalogs/MomentsML/fullimages_constimg_euclid
G_CAT=$CATS_MOM/tp-varpsf/adamom_trucat_nw/groupcat.fits
G_VCAT=$CATS_MOM/tp-varpsf/adamom_trucat_nw/groupcat.fits
G_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "adamom_flux" "adamom_rho4" "psf_adamom_g1" "psf_adamom_g2" "psf_adamom_sigma" "psf_adamom_rho4")
EPOCHS=100000
FINE_EPOCHS=5000
LEARNING_RATE=0.01

python $COMMAND  --workdir=$WORK_PATH --g_config=$G_CONFIG --g_features ${G_FEATURES[@]} --g_cat=$G_CAT --g_vcat=$G_VCAT --epochs=$EPOCHS --fine_epochs=$FINE_EPOCHS --learning_rate=$LEARNING_RATE  --validate_g --train_g --finetune
 
