#!/bin/bash

START_PATH=/users/aanavarroa/original_gitrepos/TF_MomentsML_experiments/TF_scripts_2comp
COMMAND=$START_PATH/TF_run_euclidlike_2comp.py

WORK_PATH=/vol/euclidraid4/data/aanavarroa/trainings_eu_2comp-flagship/sexcat-g-grid-trucat-nw-ss_10nodes_MAG_AUTO

POINT_MODEL_WEIGHTS=$WORK_PATH/training/members/_bestmember/bestmember_weights.ckpt
G_NORMER=$WORK_PATH/training/normers/tp_input_adamom_g1adamom_g2adamom_sigmaMAG_AUTOadamom_rho4skymad_normer.pkl

G_CONFIG=$START_PATH/g_10x10.cfg
CATS_MOM=/vol/euclidraid4/data/aanavarroa/catalogs/MomentsML/fullimages_constimg_euclid-flagship
G_CAT=$CATS_MOM/tp-bulgedisk-constpsf-constback-grid/adamom_sexcat_nw_ss/groupcat.fits
G_VCAT=$CATS_MOM/vp-bulgedisk-constpsf-constback-grid/adamom_sexcat_nw_ss/groupcat.fits
G_FEATURES=("adamom_g1" "adamom_g2" "adamom_sigma" "MAG_AUTO" "adamom_rho4" "skymad")
TARGETS=("tru_s1" "tru_s2")
EPOCHS=1000
FINE_EPOCHS=10000
LEARNING_RATE=0.1

cd $START_PATH

python $COMMAND  --workdir=$WORK_PATH --g_config=$G_CONFIG --g_features ${G_FEATURES[@]} --targets ${TARGETS[@]} --g_cat=$G_CAT --g_vcat=$G_VCAT --epochs=$EPOCHS --fine_epochs=$FINE_EPOCHS --learning_rate=$LEARNING_RATE --tru_type=2 --validate_g --train_g --finetune --nbatch=10 --use_val 
 
